//
//  FMEngineTrackParams.h
//  FMEngine
//
//  Created by boo on 2013-11-19.
//  Copyright (c) 2013 Darktree. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface FMEngineTrackParams : NSObject

@property NSString *artist; // (Required) : The artist name.
@property NSString *track; // (Required) : The track name.
@property NSString *album; // (Optional) : The album name.
@property NSNumber *trackNumber; // (Optional) : The track number of the track on the album.
@property NSString *context; // (Optional) : Sub-client version (not public, only enabled for certain API keys)
@property NSString *mbid; // (Optional) : The MusicBrainz Track ID.
@property NSNumber *duration; // (Optional) : The length of the track in seconds.
@property NSString *albumArtist; // (Optional) : The album artist - if this differs from the track artist.
@property NSString *sk; // (Required) : A session key generated by authenticating a user via the authentication protocol.

// Scrobble only parameters:
@property NSNumber *timestamp; // (Required) : The time the track started playing, in UNIX timestamp format (integer number of seconds since 00:00:00, January 1st 1970 UTC). This must be in the UTC time zone.
@property NSString *streamId; // (Optional) : The stream id for this track received from the radio.getPlaylist service, if scrobbling Last.fm radio
@property NSNumber *chosenByUser; // (Optional) : Set to 1 if the user chose this song, or 0 if the song was chosen by someone else (such as a radio station or recommendation service). Assumes 1 if not specified


+ (FMEngineTrackParams *)paramsWithArtist:(NSString *)artist track:(NSString *)track;
- (NSDictionary *)asDict;
- (NSDictionary *)asDictWithIndex:(NSUInteger)index;

@end
